spring.application.name=mycoolapp

# Wildcard to expose all actuator endpoints:
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info

management.info.env.enabled=true
info.app.name=Demo app
info.app.description=Just your basic demo app
info.app.version=1.0.0