spring.application.name=mycoolapp

# Wildcard to expose all actuator endpoints:
management.endpoints.web.exposure.include=*

# Include individual actuator endpoints:
# management.endpoints.web.exposure.include=health,info

# Exclude individual actuator endpoints:
# management.endpoints.web.exposure.exclude=health,info

management.info.env.enabled=true

# Information available at /actuator/info
info.app.name=Demo app
info.app.description=Just your basic demo app
info.app.version=1.0.0

# After adding the spring-boot-starter-security dependency,
# the following configuration overrides the default "user" username and console outputted password:
spring.security.user.name=tiger
spring.security.user.password=woods123

# Server port - Spring boot embedded server port
server.port=7070

# Context path - Set context path of the app
# All requests should be prefixed with /mycoolapp
server.servlet.context-path=/mycoolapp

###############################

# There are over 1000 properties that can be added to this file.
# Examples:
# - Log file path
# - Log level
# - Web server port
# - Web context path of the application
# - Web http session timeout
# - Actuator endpoints to include/exclude/*
# - Actuator base path
# - Security credentials
# - Data database properties URL, credentials